### PR TITLE
Add processing-java Flycheck checker

### PR DESCRIPTION
**Pull request by myrjola**
Uses the --build flag to report compilation errors.

This commit adds a new file processing-flycheck.el. It will probably have the same problem as https://github.com/ptrv/processing2-emacs/issues/7.

Here's a screenshot of the functionality in action:
image

### CODE REVIEW

**Comment by myrjola** [comment]
There is one issue regarding the checker on OSX https://github.com/processing/processing/issues/3996

**Comment by ptrv** [comment]
Thanks for the pull request. It's nice to have a flycheck checker. Was the `--build` flag introduced with Processing 3?

File: processing-flycheck.el [hunk 1]
```diff
@@ -0,0 +1,44 @@
+;;; processing-company.el --- company-mode support for processing-mode  -*- lexical-binding: t; -*-
```
Comment (ptrv) [inline processing-flycheck.el]: Needs to be changed to correct file name.

Comment (myrjola) [inline processing-flycheck.el]: Fixed as of https://github.com/myrjola/processing2-emacs/commit/bca6cb6a532b59ff187e16ab294209fea03822a7

**Comment by myrjola** [comment]
The `--build`-flag has been introduced in https://github.com/processing/processing/commit/65eabd602b4345ad974ef19102c77ec6999e3694#diff-a5d89faf34dcdd1fa7b1fb44432bd617R32. I think it has been in Processing 2 as well.

**Comment by ptrv** [comment]
To be consistent with other external flycheck checkers, the file name should be `flycheck-processing.el` and also all other occurences of `processing-flycheck` should be renamed to `flycheck-processing`

File: processing-flycheck.el [hunk 2]
```diff
@@ -0,0 +1,44 @@
+;;; processing-flycheck.el --- Flycheck checker for processing-mode  -*- lexical-binding: t; -*-
+
+;; Copyright (C) 2015  Peter Vasil
+
+;; Author: Martin Yrjölä <martin.yrjola@gmail.com>
+;; Keywords: extensions
+
```
Comment (ptrv) [inline processing-flycheck.el]: In order to make this int a MELPA recipe we need to add the version an package requires

```
;; Version: 0.1
;; Package-Requires: ((processing-mode "1.3.0") (flycheck "0.22"))
```

**Comment by myrjola** [comment]
@ptrv Thanks for pointing out the specifics regarding MELPA! They should be fixed in https://github.com/myrjola/processing2-emacs/commit/6e35f4f672e11a7b1f07ea2bd2426909cb732319

**Comment by ptrv** [comment]
Merged with https://github.com/ptrv/processing2-emacs/commit/f37f6a4d2ab65b6fa1f3cd9336d2a9713355b72a

@myrjola Thanks

I added a setup function in order to be able to autoload `flycheck-processing` and some documentation

**Comment by ptrv** [comment]
@myrjola About MELPA, would you mind taking care about sending a PR to MELPA for this recipe?

```lisp
(flycheck-processing
 :repo "ptrv/processing2-emacs"
 :fetcher github
 :files ("flycheck-processing.el"))
```

**Comment by myrjola** [comment]
Sure thing @ptrv! I created a PR https://github.com/milkypostman/melpa/pull/3206
